/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 13.5 		*/
/*  Created On : 01-pro-2017 12:53:00 				*/
/*  DBMS       : MySql 						*/
/* ---------------------------------------------------- */

SET FOREIGN_KEY_CHECKS=0 
;

/* Drop Tables */

DROP TABLE IF EXISTS `Adresa` CASCADE
;

DROP TABLE IF EXISTS `Benefit` CASCADE
;

DROP TABLE IF EXISTS `Inventura` CASCADE
;

DROP TABLE IF EXISTS `jeZahrnutaDo` CASCADE
;

DROP TABLE IF EXISTS `Krehkost` CASCADE
;

DROP TABLE IF EXISTS `Login` CASCADE
;

DROP TABLE IF EXISTS `Osoba` CASCADE
;

DROP TABLE IF EXISTS `Pozice` CASCADE
;

DROP TABLE IF EXISTS `PoziceZamestnance` CASCADE
;

DROP TABLE IF EXISTS `Regal` CASCADE
;

DROP TABLE IF EXISTS `Sekce` CASCADE
;

DROP TABLE IF EXISTS `StavRegalu` CASCADE
;

DROP TABLE IF EXISTS `StavZasilky` CASCADE
;

DROP TABLE IF EXISTS `Zakaznik` CASCADE
;

DROP TABLE IF EXISTS `Zamestnanec` CASCADE
;

DROP TABLE IF EXISTS `Zasilka` CASCADE
;

/* Create Tables */

CREATE TABLE `Adresa`
(
	`Cislopopisne` DECIMAL(6,0) NOT NULL COMMENT 'Popisné èíslo domu.',
	`Obec` VARCHAR(50) NOT NULL COMMENT 'Název obce.',
	`PSC` DECIMAL(5,0) NOT NULL COMMENT 'Poštovní smìrovací èíslo.',
	`Ulice` VARCHAR(100) NOT NULL COMMENT 'Název ulice.',
	`AdresaID` DECIMAL(8,0) NOT NULL COMMENT 'Primární klíè adresy.',
	CONSTRAINT `PK_Adresa` PRIMARY KEY (`AdresaID` ASC)
)
COMMENT = 'Definuje místo na které se zásilky odesílaji.'

;

CREATE TABLE `Benefit`
(
	`BENEFIT` VARCHAR(25) NOT NULL COMMENT 'Název benefitu sloužící jako identifikátor.',
	`POPIS` VARCHAR(400) NOT NULL COMMENT 'Detailnì vymezuje co všechno benefit poskytuje a èeho mùže zákazník využívat.',
	`PLATNOSTDO` DATETIME NULL COMMENT 'Specifikuje do kdy urèitý benefit platný.',
	CONSTRAINT `PK_Benefit` PRIMARY KEY (`BENEFIT` ASC)
)
COMMENT = 'Tabulka všech benefitù které jsou, nebo byly poskytovány.'

;

CREATE TABLE `Inventura`
(
	`Datumporizeni` DATETIME NOT NULL COMMENT 'Datum vytvoøení inventury.',
	`Dodata` DATETIME NOT NULL COMMENT 'Datum konce sledovaného období inventury.',
	`Oddata` DATETIME NOT NULL COMMENT 'Datum poèátku sledovaného období inventury.',
	`CISLOINVENTURY` DECIMAL(8,0) NOT NULL COMMENT 'Slouží zároveò jako unikátní identifikátor',
	`POPIS` VARCHAR(200) NULL COMMENT 'Slovní popis pro upøesnìní inventury.',
	CONSTRAINT `PK_Inventura` PRIMARY KEY (`CISLOINVENTURY` ASC)
)
COMMENT = 'Soupis celkového stavu zásilek skladu za vybrané èasové období.'

;

CREATE TABLE `jeZahrnutaDo`
(
	`ZasilkaID` DECIMAL(8,0) NOT NULL COMMENT 'Identifikátor zásilek zahrnutých do inventury',
	`INVENTURA` DECIMAL(8,0) NOT NULL COMMENT 'Èíslo inventury (identifikátor).'
)
COMMENT = 'Slouží pro dekompozici m:n vztahu.'

;

CREATE TABLE `Krehkost`
(
	`KREHKOST` VARCHAR(10) NOT NULL COMMENT 'Urèuje stupeò køehkosti zásilky.',
	`POPIS` VARCHAR(200) NOT NULL COMMENT 'Pro upøesnìní a detaily spojené s oznaèenou køehkostí',
	CONSTRAINT `PK_Krehkost` PRIMARY KEY (`KREHKOST` ASC)
)
COMMENT = 'Definuje urèité stupnì køehkosti zásilek.'

;

CREATE TABLE `Login`
(
	`USERNAME` VARCHAR(50) NOT NULL COMMENT 'Jméno uživatele (pøiøazeno každému zamìstnanci, pokud ho zamìstnanec nemá, dostane defaultní)',
	`PW` VARCHAR(50) NOT NULL COMMENT 'Heslo, mìl by tu být hash, ale pro úèely této školní práce tam bude plain text.',
	CONSTRAINT `PK_Login` PRIMARY KEY (`USERNAME` ASC)
)
COMMENT = 'Tabulka uchovávající loginy všech uživatelù.'

;

CREATE TABLE `Osoba`
(
	`Datumnarozeni` DATETIME NULL COMMENT 'Datum narození. Nemusí být nutnì u každé osoby vyplnìno.',
	`Jmeno` VARCHAR(100) NOT NULL COMMENT 'Køestní jméno odesilatele.',
	`Prijmeni` VARCHAR(100) NOT NULL COMMENT 'Pøíjmení odesilatele.',
	`Rodnecislo` DECIMAL(10,0) NULL COMMENT 'Rodné èíslo. Nemusí být nutnì u každé osoby vyplnìno.',
	`OsobaID` DECIMAL(8,0) NOT NULL COMMENT 'Identifikátor osoby.',
	`AdresaID` DECIMAL(8,0) NOT NULL COMMENT 'Cizí klíè na adresaID.',
	CONSTRAINT `PK_Osoba` PRIMARY KEY (`OsobaID` ASC)
)
COMMENT = 'Tabulka, která repzerentuje jednu osobu. Daná osoba mùže, ale nemusí být zároveò zákazníkem z pohledu skladu. Všechny osoby musí mít vyplnìnou adresu, jméno a pøíjmení.'

;

CREATE TABLE `Pozice`
(
	`Patro` DECIMAL(8,0) NOT NULL COMMENT 'Patro v konkrétním regálu.',
	`Sektor` VARCHAR(3) NOT NULL COMMENT 'Každá police je rozdìlena na nìkolik sektorù. Sektor definuje umístìní (sloupec) v patøe.',
	`ZasilkaID` DECIMAL(8,0) NULL COMMENT 'Zásilka která mùže být umístìna na konkrétní pozici.',
	`RegalID` DECIMAL(8,0) NOT NULL COMMENT 'Identifikátor regálu ve kterém je tato pozice,',
	`POZICEID` VARCHAR(50) NOT NULL COMMENT 'Identifikátor konkrétní pozice,',
	CONSTRAINT `PK_Pozice` PRIMARY KEY (`POZICEID` ASC)
)
COMMENT = 'Jedno konkrétní místo v regálu na které se zásilky ukládají.'

;

CREATE TABLE `PoziceZamestnance`
(
	`POZICE` VARCHAR(50) NOT NULL COMMENT 'Pozice které jsou pøidìleny zamìstnancùm zásilkového skladu.',
	`POPIS` VARCHAR(50) NULL COMMENT 'Slovní popis pozice.',
	CONSTRAINT `PK_Pozice` PRIMARY KEY (`POZICE` ASC)
)
COMMENT = 'Pracovní zaøazení zamìstnance.'

;

CREATE TABLE `Regal`
(
	`Nosnost` DOUBLE(8,2) NOT NULL COMMENT 'Maximální hmotnost, kterou daný regál unese.',
	`Oznaceni` VARCHAR(10) NOT NULL COMMENT 'Oznaèení regálu (štítek který je nalepen na regálu)',
	`RegalID` DECIMAL(8,0) NOT NULL COMMENT 'Identifikátor regálu',
	`SekceID` DECIMAL(8,0) NOT NULL COMMENT 'Odkaz na identifikátor sekce (v jaké sekci regál je).',
	`STAV` VARCHAR(50) NOT NULL,
	`POPIS` VARCHAR(200) NULL COMMENT 'Libovolná poznámka k urèitému regálu (napøíklad popis poškození regálu).',
	CONSTRAINT `PK_Regal` PRIMARY KEY (`RegalID` ASC)
)
COMMENT = 'Nìkolik pater úložného prostoru, které se dìlí na jednotlivé pozice.'

;

CREATE TABLE `Sekce`
(
	`Oznaceni` VARCHAR(10) NOT NULL COMMENT 'Sekce jsou znaèené písmeny abecedy (první sekce A, za ní B atd.) Oznaèení jsou unikátní.',
	`POPIS` VARCHAR(50) NULL COMMENT 'Pro upøesnìní místa, kde se sekce nachází.',
	`SekceID` DECIMAL(8,0) NOT NULL COMMENT 'Identifikátor sekce.',
	CONSTRAINT `PK_Sekce` PRIMARY KEY (`SekceID` ASC)
)
COMMENT = 'Sekce oznaèuje urèitou èást skladovací místnosti, obsahuje vždy nìkolik regálù.'

;

CREATE TABLE `StavRegalu`
(
	`STAV` VARCHAR(20) NOT NULL COMMENT 'Definuje stav do kterého se mùže regál dostat. (OK/poškozený/..)',
	`POPIS` VARCHAR(200) NOT NULL COMMENT 'Upøesnìní toho, co daný stav znamená.',
	CONSTRAINT `PK_Table1` PRIMARY KEY (`STAV` ASC)
)
COMMENT = 'Tabulku udržující možné stavy do které se regál mùže dostat.'

;

CREATE TABLE `StavZasilky`
(
	`STAV` VARCHAR(20) NOT NULL COMMENT 'Stav ve kterém se zásilka právì nachází.',
	`POPIS` VARCHAR(200) NOT NULL COMMENT 'Popisuje detaily urèitého stavu.',
	CONSTRAINT `PK_StavZasilky` PRIMARY KEY (`STAV` ASC)
)
COMMENT = 'Tabulka udržující stavy do kterých se mùže zásilka dostat.'

;

CREATE TABLE `Zakaznik`
(
	`Benefit` VARCHAR(25) NOT NULL COMMENT 'Zvýhodnìní, na které má zákazní nárok.',
	`Email` VARCHAR(50) NOT NULL COMMENT 'Emailová adresa. Nepovinný údaj.',
	`Ic` DECIMAL(10,0) NULL COMMENT 'IÈ firmy, kterou zákazník jako právnická osoba zastupuje. Pokud je zákazník fyzickou osobou, nebude tento atribut vyplnìn.',
	`Telcislo` DECIMAL(12,0) NULL COMMENT 'Telefonní èíslo zákazníka. Nepovinný údaj.',
	`ZakaznikID` DECIMAL(8,0) NOT NULL COMMENT 'Identifikátor zákazníka',
	`OsobaID` DECIMAL(8,0) NOT NULL COMMENT 'Odkaz na identifikátor osoby.',
	CONSTRAINT `PK_Zakaznik` PRIMARY KEY (`ZakaznikID` ASC)
)
COMMENT = 'Je konkrétní osoba, která využívá služby zásilkového skladu.'

;

CREATE TABLE `Zamestnanec`
(
	`Email` VARCHAR(50) NOT NULL COMMENT 'Emailová adresa zamìstnance.',
	`POZICE` VARCHAR(50) NULL COMMENT 'Funkce (pozice) zamìstnance v zásilkovém skladu.',
	`Telcislo` DECIMAL(12,0) NULL COMMENT 'Telefonní èíslo zamìstnance.',
	`Username` VARCHAR(50) NOT NULL COMMENT 'Unikátní jméno zamìstnance sloužící pro pøihlášení do systému.',
	`OSOBA` DECIMAL(8,0) NOT NULL COMMENT 'Odkaz na osobu kterou je zamìstnanec.',
	`ZamestnanecID` DECIMAL(8,0) NOT NULL COMMENT 'Identifikátor zamìstnance.',
	CONSTRAINT `PK_Zamestnanec` PRIMARY KEY (`ZamestnanecID` ASC)
)
COMMENT = 'Tabulka udržující základní informace a login každého zamìstnance zásilkového skladu.'

;

CREATE TABLE `Zasilka`
(
	`Datumprijeti` DATETIME NOT NULL COMMENT 'Datum které zadá sekretáøka pøi pøijetí zásilky. Díky nìmu bude také možné vypoèítat jak dlouho už je zásilka uskladnìna.',
	`Datumvydani` DATETIME NULL COMMENT 'Kdy byla zásilka vydána pro osobní odbìr, nebo pøedána poštì.',
	`Hmotnost` DOUBLE(8,2) NOT NULL COMMENT 'Hmotnost zásilky.',
	`Kodzasilky` VARCHAR(50) NOT NULL COMMENT 'Vygenerovaný unikátní kód.(generuje IS)',
	`Krehkost` VARCHAR(10) NOT NULL COMMENT 'Urèuje, zda se jedná o zásilku bytelnou nebo o snadno rozbitnou.',
	`ZasilkaID` DECIMAL(8,0) NOT NULL COMMENT 'ID zásilky v databázi',
	`ODESILATEL` DECIMAL(8,0) NOT NULL COMMENT 'Odesilatel zásilky, musí být vždy uveden.',
	`PRIJEMCE` DECIMAL(8,0) NOT NULL COMMENT 'Prijemce',
	`STAV` VARCHAR(20) NOT NULL,
	CONSTRAINT `PK_Zasilka` PRIMARY KEY (`ZasilkaID` ASC)
)
COMMENT = 'Tabulka všech pøijatých zásilek.'

;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE `jeZahrnutaDo` 
 ADD INDEX `IXFK_JEZAHRNUTADO` (`INVENTURA` ASC)
;

ALTER TABLE `jeZahrnutaDo` 
 ADD INDEX `IXFK_jeZahrnutaDo_Zasilka` (`ZasilkaID` ASC)
;

ALTER TABLE `Osoba` 
 ADD INDEX `IXFK_Osoba_bydliNa` (`AdresaID` ASC)
;

ALTER TABLE `Pozice` 
 ADD INDEX `IXFK_JEZDEUMISTEN` (`ZasilkaID` ASC)
;

ALTER TABLE `Pozice` 
 ADD INDEX `IXFK_Pozice_jeV` (`RegalID` ASC)
;

ALTER TABLE `Regal` 
 ADD INDEX `IXFK_Regal_jeUmisten` (`SekceID` ASC)
;

ALTER TABLE `Regal` 
 ADD INDEX `IXFK_Regal_StavRegalu` (`STAV` ASC)
;

ALTER TABLE `Zakaznik` 
 ADD INDEX `IXFK_Zakaznik_Benefit` (`Benefit` ASC)
;

ALTER TABLE `Zakaznik` 
 ADD INDEX `IXFK_Zakaznik_je` (`OsobaID` ASC)
;

ALTER TABLE `Zamestnanec` 
 ADD INDEX `IXFK_Zamestnanec_Login` (`Username` ASC)
;

ALTER TABLE `Zamestnanec` 
 ADD INDEX `IXFK_Zamestnanec_Osoba` (`OSOBA` ASC)
;

ALTER TABLE `Zamestnanec` 
 ADD INDEX `IXFK_Zamestnanec_PoziceZa01` (`POZICE` ASC)
;

ALTER TABLE `Zasilka` 
 ADD INDEX `IXFK_ODESILATEL` (`ODESILATEL` ASC)
;

ALTER TABLE `Zasilka` 
 ADD INDEX `IXFK_PRIJEMCE` (`PRIJEMCE` ASC)
;

ALTER TABLE `Zasilka` 
 ADD INDEX `IXFK_Zasilka_Krehkost` (`Krehkost` ASC)
;

ALTER TABLE `Zasilka` 
 ADD INDEX `IXFK_Zasilka_StavZasilky` (`STAV` ASC)
;

/* Create Foreign Key Constraints */

ALTER TABLE `jeZahrnutaDo` 
 ADD CONSTRAINT `FK_jeZahrnutaDo_Zasilka`
	FOREIGN KEY (`ZasilkaID`) REFERENCES `Zasilka` (`ZasilkaID`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `jeZahrnutaDo` 
 ADD CONSTRAINT `FK_jeZahrnutaDo_Inventura`
	FOREIGN KEY (`INVENTURA`) REFERENCES `Inventura` (`CISLOINVENTURY`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `Osoba` 
 ADD CONSTRAINT `FK_Osoba_bydliNa`
	FOREIGN KEY (`AdresaID`) REFERENCES `Adresa` (`AdresaID`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `Pozice` 
 ADD CONSTRAINT `FK_JEZDEUMISTEN`
	FOREIGN KEY (`ZasilkaID`) REFERENCES `Zasilka` (`ZasilkaID`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `Pozice` 
 ADD CONSTRAINT `FK_Pozice_jeV`
	FOREIGN KEY (`RegalID`) REFERENCES `Regal` (`RegalID`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `Regal` 
 ADD CONSTRAINT `FK_Regal_StavRegalu`
	FOREIGN KEY (`STAV`) REFERENCES `StavRegalu` (`STAV`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `Regal` 
 ADD CONSTRAINT `FK_Regal_jeUmisten`
	FOREIGN KEY (`SekceID`) REFERENCES `Sekce` (`SekceID`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `Zakaznik` 
 ADD CONSTRAINT `FK_Zakaznik_Benefit`
	FOREIGN KEY (`Benefit`) REFERENCES `Benefit` (`BENEFIT`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `Zakaznik` 
 ADD CONSTRAINT `FK_Zakaznik_je`
	FOREIGN KEY (`OsobaID`) REFERENCES `Osoba` (`OsobaID`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `Zamestnanec` 
 ADD CONSTRAINT `FK_PRACUJE_NA`
	FOREIGN KEY (`POZICE`) REFERENCES `PoziceZamestnance` (`POZICE`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `Zamestnanec` 
 ADD CONSTRAINT `FK_Zamestnanec_Login`
	FOREIGN KEY (`Username`) REFERENCES `Login` (`USERNAME`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `Zamestnanec` 
 ADD CONSTRAINT `FK_Zamestnanec_Osoba`
	FOREIGN KEY (`OSOBA`) REFERENCES `Osoba` (`OsobaID`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `Zasilka` 
 ADD CONSTRAINT `FK_ODESILATEL`
	FOREIGN KEY (`ODESILATEL`) REFERENCES `Osoba` (`OsobaID`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `Zasilka` 
 ADD CONSTRAINT `FK_PRIJEMCE`
	FOREIGN KEY (`PRIJEMCE`) REFERENCES `Osoba` (`OsobaID`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `Zasilka` 
 ADD CONSTRAINT `FK_Zasilka_Krehkost`
	FOREIGN KEY (`Krehkost`) REFERENCES `Krehkost` (`KREHKOST`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `Zasilka` 
 ADD CONSTRAINT `FK_Zasilka_StavZasilky`
	FOREIGN KEY (`STAV`) REFERENCES `StavZasilky` (`STAV`) ON DELETE No Action ON UPDATE No Action
;

SET FOREIGN_KEY_CHECKS=1 
;
